services:
  still-forest-dot-dev:
    container_name: still-forest-dot-dev
    image: ghcr.io/still-forest/still-forest-dot-dev:latest
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=production
      - APP_ENV=production
      - OPERATOR_EMAIL_URL=http://operator.test/api/email
      - LOKI_HOST=https://logs-prod-eu-west-0.grafana.net
      - LOKI_USERNAME=your-grafana-instance-id
      - LOKI_API_KEY=your-grafana-api-key
    restart: unless-stopped
