name: Publish to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - "!renovate/**"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
        with:
          driver: docker-container
          # This explicitly sets the driver to use containers instead of the default Docker driver

      - name: Build and push image
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/still-forest-dot-dev:latest .
            docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/still-forest-dot-dev:latest
          else
            docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/still-forest-dot-dev:next .
            docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/still-forest-dot-dev:next
          fi
