name: Publish to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - "!renovate/**"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
        with:
          driver: docker-container
          # This explicitly sets the driver to use containers instead of the default Docker driver

      - name: Build and push image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ secrets.GHCR_USERNAME }}/still-forest-dot-dev:${{ github.ref == 'refs/heads/main' && 'latest' || 'next' }}
            ghcr.io/${{ secrets.GHCR_USERNAME }}/still-forest-dot-dev:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ secrets.GHCR_USERNAME }}/still-forest-dot-dev:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ secrets.GHCR_USERNAME }}/still-forest-dot-dev:buildcache,mode=max
